package d;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import a.DBManager;

/*
 * zc.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class zhuce extends javax.swing.JFrame {

	/** Creates new form zc */
	public zhuce() {
		initComponents();

		ImageIcon img = new ImageIcon("images/03.jpg");
		JLabel bg = new JLabel(img);
		bg.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
		this.getLayeredPane().add(bg, new Integer(Integer.MIN_VALUE));
		JPanel jp = (JPanel) this.getContentPane();
		jp.setOpaque(false);//透明
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		jPasswordField2 = new javax.swing.JPasswordField();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();

		jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor(
				"Button.light"));
		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u7528\u6237\u6ce8\u518c"));
		jPanel1.setLayout(null);

		jButton2.setFont(new java.awt.Font("楷体", 0, 18));
		jButton2.setText("\u8fd4\u56de");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
			//	jButton2ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton2);
		jButton2.setBounds(290, 320, 90, 50);

		jButton1.setFont(new java.awt.Font("楷体", 0, 18));
		jButton1.setText("\u6ce8\u518c");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
			//	jButton1ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton1);
		jButton1.setBounds(140, 320, 90, 50);

		jLabel6.setForeground(new java.awt.Color(255, 51, 51));
		jLabel6.setText("*\u8bf7\u518d\u8f93\u5165\u4e00\u6b21\u5bc6\u7801*");
		jPanel1.add(jLabel6);
		jLabel6.setBounds(370, 240, 110, 160);

		jLabel4.setForeground(new java.awt.Color(255, 51, 51));
		jLabel4
				.setText("*\u8bf7\u586b\u5199\u8981\u6ce8\u518c\u7684\u7528\u6237\u540d*");

		jLabel5.setForeground(new java.awt.Color(255, 51, 51));
		jLabel5.setText("*\u8bf7\u8f93\u5165\u5bc6\u7801*");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBounds(new java.awt.Rectangle(500, 250, 0, 0));
		setFocusTraversalPolicyProvider(true);
		setMinimumSize(new java.awt.Dimension(530, 450));
		getContentPane().setLayout(null);

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
			//	jTextField1ActionPerformed(evt);
			}
		});
		getContentPane().add(jTextField1);
		jTextField1.setBounds(250, 70, 160, 30);

		jLabel1.setFont(new java.awt.Font("楷体", 0, 24));
		jLabel1.setText("\u7528\u6237\u540d\uff1a");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(100, 50, 110, 80);

		jLabel2.setFont(new java.awt.Font("楷体", 0, 24));
		jLabel2.setText("\u5bc6  \u7801\uff1a");
		getContentPane().add(jLabel2);
		jLabel2.setBounds(100, 120, 110, 60);
		getContentPane().add(jPasswordField1);
		jPasswordField1.setBounds(250, 140, 160, 30);

		jLabel3.setFont(new java.awt.Font("楷体", 0, 24));
		jLabel3.setText("\u786e\u8ba4\u5bc6\u7801\uff1a");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(90, 210, 130, 29);
		getContentPane().add(jPasswordField2);
		jPasswordField2.setBounds(250, 210, 160, 30);

		jButton3.setText("\u6ce8\u518c");
		jButton3.setActionCommand("jButon3");
		jButton3.setAutoscrolls(true);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton3);
		jButton3.setBounds(130, 340, 110, 60);

		jButton4.setText("\u8fd4\u56de");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton4);
		jButton4.setBounds(301, 345, 120, 60);

		pack();
	}// </editor-fold>
	void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		login a = new login();
		a.setVisible(true);
		this.dispose();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String username = jTextField1.getText();
		String password = jPasswordField1.getText();
		String confirmpassword = jPasswordField2.getText();
		try {
			Connection con = DBManager.getConnection();
			Statement stmt = null;
			//ResultSet rs = null;
			stmt = con.createStatement();
			if (jTextField1.getText().trim().equals("")
					|| jPasswordField1.getText().trim().equals("")
					|| jPasswordField2.getText().trim().equals("")) {
				JOptionPane.showMessageDialog(this, "信息不能为空！");
				jTextField1.setText("");
				jPasswordField1.setText("");
				jPasswordField2.setText("");
			} else {
				if (jPasswordField1.getText().equals(
						(jPasswordField2.getText()))) {
					stmt.executeUpdate("insert into user values" + "('"
							+ username + "','" + password + "')");
					JOptionPane.showMessageDialog(this, "已成功注册！");
					jTextField1.setText("");
					jPasswordField1.setText("");
					jPasswordField2.setText("");
				} else {
					JOptionPane.showMessageDialog(this, "密码错误,请重新输入！");
					jPasswordField1.setText("");
					jPasswordField2.setText("");
				}

			}
			DBManager.close1(stmt);
			//	DBManager.close(rs);	
			//DBManager.close1(con);

		} catch (SQLException e) {

			e.printStackTrace();
		}
	}

	/**
	 * @param args the command line arguments
	 */

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new zhuce().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}